### ISSUE TITLE
Add Normalize.css to the landing page

### ISSUE THREAD

**Issue by manghidev** [KananPass/site#12]
@manghidev Another thing we could use for consistent styles is **[Normalize.css](https://necolas.github.io/normalize.css/).**
It provides out of the box element stylings for modern sites, making the website more consistent on it's styles.

You could add it to a commit before we close the PR, or we can add it l8r, up to you! :frog:

_Originally posted by @VCAngel in https://github.com/KananPass/site/issues/11#issuecomment-2231355717_

**Comment by VCAngel** [comment]
My bad! :skull: 
Upon quick investigation, Tailwind actually uses normalize! 

Refs:
- [Preflight  - Tailwind CSS](https://tailwindcss.com/docs/preflight)
- [modern-normalize](https://github.com/sindresorhus/modern-normalize)
